version: '3.9'
services:
    db:
        image: postgres:alpine3.17
        restart: always
        environment:
            POSTGRES_USER: "broccoli"
            POSTGRES_PASSWORD: "qXmZZ7U8"
            POSTGRES_DB: "schools"
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=your_password_here
